/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pbo.praktikum_9;

import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class FrmKalkulator extends javax.swing.JFrame {

    /**
     * Creates new form FrmKalkulator
     */
    public FrmKalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNilai1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNilai2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtHasil = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnKali = new javax.swing.JButton();
        btnBagi = new javax.swing.JButton();
        btnKurang = new javax.swing.JButton();
        btnPangkat = new javax.swing.JButton();
        btnAkar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nilai Pertama");

        txtNilai1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNilai1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Nilai Kedua");

        txtNilai2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNilai2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Hasil");

        txtHasil.setEditable(false);
        txtHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHasilActionPerformed(evt);
            }
        });

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnKali.setText("Kali");
        btnKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaliActionPerformed(evt);
            }
        });

        btnBagi.setText("Bagi");
        btnBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBagiActionPerformed(evt);
            }
        });

        btnKurang.setText("Kurang");
        btnKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKurangActionPerformed(evt);
            }
        });

        btnPangkat.setText("Pangkat");
        btnPangkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPangkatActionPerformed(evt);
            }
        });

        btnAkar.setText("Akar");
        btnAkar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAkarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBagi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPangkat, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAkar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addGap(54, 54, 54)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtHasil)
                                .addComponent(txtNilai1)
                                .addComponent(txtNilai2, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnKali, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6))))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNilai1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNilai2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnKurang)
                    .addComponent(btnKali))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBagi)
                    .addComponent(btnPangkat)
                    .addComponent(btnAkar))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNilai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNilai1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNilai1ActionPerformed

    private void txtNilai2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNilai2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNilai2ActionPerformed

    private void txtHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHasilActionPerformed

    private void btnBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBagiActionPerformed
        // TODO add your handling code here:
        try{
         int nilai1 = Integer.parseInt(txtNilai1.getText());
         int nilai2 = Integer.parseInt(txtNilai2.getText());
         float hasil = (float) nilai1 / nilai2;
         txtHasil.setText(Float.toString(hasil));
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Inputan Masih Kosong !");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Ada Error !");
        }
    }//GEN-LAST:event_btnBagiActionPerformed

    private void btnKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaliActionPerformed
        // TODO add your handling code here:
        try{
         int nilai1 = Integer.parseInt(txtNilai1.getText());
         int nilai2 = Integer.parseInt(txtNilai2.getText());
         float hasil = (float) nilai1 * nilai2;
         txtHasil.setText(Float.toString(hasil));
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Inputan Masih Kosong !");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Ada Error !");
        } 
    }//GEN-LAST:event_btnKaliActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        try{
         int nilai1 = Integer.parseInt(txtNilai1.getText());
         int nilai2 = Integer.parseInt(txtNilai2.getText());
         float hasil = (float) nilai1 + nilai2;
         txtHasil.setText(Float.toString(hasil));
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Inputan Masih Kosong !");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Ada Error !");
        } 
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKurangActionPerformed
        // TODO add your handling code here:
        try{
         int nilai1 = Integer.parseInt(txtNilai1.getText());
         int nilai2 = Integer.parseInt(txtNilai2.getText());
         float hasil = (float) nilai1 - nilai2;
         txtHasil.setText(Float.toString(hasil));
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Inputan Masih Kosong !");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Ada Error !");
        }
    }//GEN-LAST:event_btnKurangActionPerformed

    private void btnPangkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPangkatActionPerformed
        // TODO add your handling code here:
        try{
         int nilai1 = Integer.parseInt(txtNilai1.getText());
         int nilai2 = Integer.parseInt(txtNilai2.getText());
         float hasil = (float) Math.pow(nilai1, nilai2);
         txtHasil.setText(Float.toString(hasil));
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Inputan Masih Kosong !");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Ada Error !");
        }
    }//GEN-LAST:event_btnPangkatActionPerformed
    private void operasiAkar(){
        int nilai1 = Integer.parseInt(txtNilai1.getText());
        int nilai2 = Integer.parseInt(txtNilai2.getText());
        float hasil;
        if(nilai2 == 0){
           hasil = (float)(Math.sqrt(nilai1));
        } else {
           hasil = (float)(Math.sqrt(nilai2));
        }
        txtHasil.setText(Float.toString(hasil));
    }
    private void btnAkarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAkarActionPerformed
        // TODO add your handling code here:
        try{
            operasiAkar();    
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Inputan Masih Kosong !");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Ada Error !");
        }
    }//GEN-LAST:event_btnAkarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmKalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAkar;
    private javax.swing.JButton btnBagi;
    private javax.swing.JButton btnKali;
    private javax.swing.JButton btnKurang;
    private javax.swing.JButton btnPangkat;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtHasil;
    private javax.swing.JTextField txtNilai1;
    private javax.swing.JTextField txtNilai2;
    // End of variables declaration//GEN-END:variables
}
